# This is used by Travis CI site in
# order to build and test online.

language: cpp

matrix:
  include:
    - env: DIRECTORY="apps/"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gnuplot
      before_script:
        - CXX=g++-7
        - $CXX --version

script:
    - cd $DIRECTORY
    - cmake .
    - make -j
    - ctest -V
