# This is used by Travis CI site in
# order to build and test online.

language: cpp

matrix:
  include:
    - env: DIRECTORY="XCSP3"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - g++-7
            - valgrind
            - clang-format-5.0
            - gnuplot
      before_script:
        - CXX="g++-7"
        - $CXX --version

script:
  - cd $DIRECTORY
  - cmake .
  - make -j
  - ctest -V
